version: "3.9"

# volumes:
#   celery_volume:

networks:
  celery_network:
    name: celery_network
    driver: bridge

services:
  celery_app:
    build: ./admin/celery_admin
    container_name: celery_app
    profiles:
    - "all"
    - "admin"
    command: bash -c "celery -A service worker -l info" 
    # env_file:
    #     - ./env/app.env
    # volumes:
    #     - ./app/data:/home/data
    #     - ./app/src/service:/home/service
      
  celery-beat:
    build: ./admin/celery_admin
    container_name: celery_beat
    profiles:
    - "all"
    - "admin"
    command: bash -c "celery -A service beat -l info" 
    # env_file:
    #     - ./env/app.env
    # volumes:
    #     - ./app/data:/home/data
    #     - ./app/src/service:/home/service
