version: '3.9'

networks:
  application_network:

volumes:
  nginx_logs:
  pg_volume:
  nginx_volume:
  redis_volume:

include:
  - ./deploy/mongo/docker-compose.yml
  - ./deploy/elk/docker-compose.yml
  - ./deploy/kafka/docker-compose.yml
  - ./deploy/clickhouse/docker-compose.yml
  - ./deploy/elastic/docker-compose.yml

services:
  db:
    container_name: postgres
    profiles:
      - "all"
      - "etl"
      - "auth"
      - "admin"
    image: postgres:13.0-alpine
    volumes:
      - pg_volume:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      - application_network

  redis:
    container_name: redis
    profiles:
      - "all"
      - "api"
      - "auth"
    image: redis:7.0.5
    restart: always
    volumes:
      - redis_volume:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    expose:
      - 6379
    networks:
      - application_network

  jaeger:
    container_name: jaeger
    profiles:
      - "all"
    image: jaegertracing/all-in-one:latest
    expose:
      - "6831"
      - "16686"
    depends_on:
      auth:
        condition: service_started
    networks:
      - application_network

  etl:
    container_name: etl
    profiles:
      - "all"
      - "etl"
    build:
      context: etl
    restart: always
    env_file:
      - .env
    depends_on:
      elastic_migrate:
        condition: service_completed_successfully
      db:
        condition: service_started
    networks:
      - application_network

  ugc_etl:
    container_name: ugc_etl
    profiles:
      - "all"
      - "ugc_etl"
    build: ./ugc_etl
    networks:
      - application_network
    env_file:
      - .env
    depends_on:
      broker:
        condition: service_healthy
      clickhouse1:
        condition: service_healthy

  api:
    container_name: api
    profiles:
      - "all"
      - "api"
    build: ./api
    image: movies_api
    depends_on:
      elastic_migrate:
        condition: service_completed_successfully
      redis:
        condition: service_started
    expose:
      - "8001"
    env_file:
      - .env
    networks:
      - application_network

  auth:
    container_name: auth
    profiles:
      - "all"
      - "auth"
    build: ./auth
    image: movies_auth
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_started
    expose:
      - "8002"
    env_file:
      - .env
    networks:
      - application_network

  admin:
    container_name: admin
    profiles:
      - "all"
      - "admin"
    build: ./admin
    image: movies_admin
    depends_on:
      db:
        condition: service_started
    expose:
      - "8000"
    env_file:
      - .env
    networks:
      - application_network
    volumes:
      - nginx_volume:/opt/app/static

  ugc_api:
    container_name: ugc_api
    profiles:
      - "all"
      - "ugc_api"
    build: ./ugc
    image: movies_ugc
    depends_on:
      broker:
        condition: service_healthy
    expose:
      - "8003"
    env_file:
      - .env
    networks:
      - application_network

  social_api:
    container_name: social_api
    profiles:
      - "all"
      - "social_api"
    build: ./social
    image: movies_social
    depends_on:
      mongos:
        condition: service_started
    expose:
      - "8010"
    env_file:
      - .env
    networks:
      - application_network

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./deploy/nginx/configs:/etc/nginx/conf.d:ro
      - nginx_volume:/opt/app/static
      - nginx_logs:/var/log/nginx/
    ports:
      - "80:80"
    networks:
      - application_network
