version: "3.9"

networks:
  application_network:

volumes:
  nginx_logs:

include:
  - ./deploy/mongo/docker-compose.yml
  - ./deploy/elk/docker-compose.yml

services:
  social_api:
    container_name: social_api
    build: ./social
    image: movies_social
    expose:
      - "8010"
    ports:
      - "8010:8010"
    env_file:
      - .env
    networks:
      - application_network

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./deploy/elk/nginx-test-config:/etc/nginx/conf.d:ro
      - nginx_logs:/var/log/nginx/
    depends_on:
      social_api:
        condition: service_started
      logstash:
        condition: service_started
    ports:
      - "80:80"
    networks:
      - application_network

  nginx_filebeat:
    container_name: nginx_filebeat
    image: elastic/filebeat:7.17.10
    volumes:
      - nginx_logs:/var/log/nginx:ro
      - ./deploy/elk/nginx-filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    depends_on:
      - nginx
      - logstash
      - elk-elastic
      - kibana
    links:
      - logstash
    command: filebeat -e -strict.perms=false -c filebeat.yml
    networks:
      - application_network
