"""initial migration

Revision ID: 5a2fd9563d43
Revises: 
Create Date: 2023-08-01 18:16:24.964233

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5a2fd9563d43'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_info',
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('password_hash', sa.String(), nullable=False),
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk__user_info'))
                    )
    op.create_table('user_session',
                    sa.Column('user_info_id', sa.Uuid(), nullable=False),
                    sa.Column('refresh_token', sa.String(), nullable=False),
                    sa.Column('session_type', postgresql.ENUM('NATIVE', name='user_session_type', metadata=MetaData()),
                              nullable=True),
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.ForeignKeyConstraint(['user_info_id'], ['user_info.id'],
                                            name=op.f('fk__user_session__user_info_id__user_info')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk__user_session'))
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_session')
    op.drop_table('user_info')
    # ### end Alembic commands ###
