"""update usersessions

Revision ID: a6ab8d85f09e
Revises: f73c583a8318
Create Date: 2023-08-14 21:47:21.833908

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a6ab8d85f09e'
down_revision = 'f73c583a8318'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_session', 'user_agent',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='auth')
    op.drop_column('user_session', 'refresh_token', schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_session', sa.Column('refresh_token', sa.VARCHAR(), autoincrement=False, nullable=False), schema='auth')
    op.alter_column('user_session', 'user_agent',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='auth')
    # ### end Alembic commands ###
