"""Add columns for UserSession

Revision ID: f73c583a8318
Revises: 7998e07da9a4
Create Date: 2023-08-12 19:17:36.640478

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f73c583a8318'
down_revision = '7998e07da9a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_session', sa.Column('refresh_token_jti', sa.String(), nullable=False), schema='auth')
    op.add_column('user_session', sa.Column('start_at', sa.DateTime(), nullable=False), schema='auth')
    op.add_column('user_session', sa.Column('end_at', sa.DateTime(), nullable=True), schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_session', 'end_at', schema='auth')
    op.drop_column('user_session', 'start_at', schema='auth')
    op.drop_column('user_session', 'refresh_token_jti', schema='auth')
    # ### end Alembic commands ###
