# Generated by Django 4.1.7 on 2023-10-29 15:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_zone', models.CharField(max_length=12, verbose_name='Time zone')),
                ('phone_number', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Phone number')),
                ('avatar_link', models.URLField(blank=True, null=True, verbose_name='Avatar link')),
                ('avatar_status', models.CharField(choices=[('WITHOUT', 'Without'), ('ON_INSPECTION', 'On Inspection'), ('ACCEPTED', 'Accepted'), ('NON_ACCEPTED', 'Non Accepted')], default='WITHOUT', max_length=28, verbose_name='Avatar status')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
