# Generated by Django 4.1.7 on 2023-10-03 15:03

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('html_template', models.TextField()),
                ('attributes', models.JSONField()),
            ],
            options={
                'verbose_name': 'template',
                'verbose_name_plural': 'templates',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('users_ids', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), size=None)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.template')),
            ],
            options={
                'verbose_name': 'mailing',
                'verbose_name_plural': 'mailings',
            },
        ),
    ]
