# Generated by Django 4.1.7 on 2023-10-11 16:04

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE SCHEMA IF NOT EXISTS notification     
            """,
            reverse_sql='DROP SCHEMA IF EXISTS notification',
        ),

        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('html_template', models.TextField()),
                ('attributes', models.JSONField()),
            ],
            options={
                'verbose_name': 'template',
                'verbose_name_plural': 'templates',
                'db_table': 'notification"."template',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receiver_ids', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), size=None)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('IN_PROGRESS', 'In progress'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='CREATED', max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('template_params', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.template')),
            ],
            options={
                'verbose_name': 'mailing',
                'verbose_name_plural': 'mailings',
                'db_table': 'notification"."mailing',
            },
        ),
    ]
