# Generated by Django 4.1.7 on 2023-10-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
