version: "3.9"

volumes:
  elastic_volume:

networks:
  elastic_network:
    name:   elastic_network
    driver: bridge

x-elastic-profiles:
  &elastic-profiles
  profiles:
    - "all"
    - "elastic"
    - "etl"
    - "api"

services:
  elasticsearch:
    container_name: elastic
    <<: *elastic-profiles
    image: elasticsearch:8.6.2
    restart: always
    environment:
      - "xpack.security.enabled=false"
      - "discovery.type=single-node"
      - "ingest-geoip.enabled: false"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    expose:
      - '9200'
    volumes:
      - elastic_volume:/opt/elasticsearch/data
    healthcheck:
      test: curl --fail http://elasticsearch:9200/_cat/indices?v || exit 1
      interval: 10s
      retries: 5
    mem_limit: 4g
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
        - elastic_network

  elastic_migrate:
    container_name: elastic_migrate
    <<: *elastic-profiles
    build: ./elastic_migrate
    env_file:
      - ../../.env
    networks:
        - elastic_network
