version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres:13.0-alpine
    volumes:
      - pg_volume:/var/lib/postgresql/data/
    ports:
        - "5432:5432"
    env_file:
      - ../.env
    networks:
      - application_network

networks:
  application_network:

volumes:
  pg_volume: