@startuml
'!theme vibrant

collections OtherAPIs
component CeleryBeat
component NotificationAPI
component NotificationAdmin
component RabbitMQ
component AuthAPI
collections EmailWorkers
collections WebsocketWorkers

database NotificationsDb
database MessageTemplates


OtherAPIs -down-> NotificationAPI: События-триггеры\nрассылки
CeleryBeat --> NotificationAPI: Запуск\nрассылки
NotificationAPI -down-> RabbitMQ
RabbitMQ -down-> EmailWorkers
RabbitMQ -down-> WebsocketWorkers
NotificationAdmin -down-> NotificationAPI: Запуск рассылки
NotificationAdmin <-down-> CeleryBeat: управление\nпериодическими\nрассылками
AuthAPI --> EmailWorkers: Данные о\nпользователях
AuthAPI --> WebsocketWorkers: Данные о\nпользователях

EmailWorkers <-- MessageTemplates: Шаблоны сообщений
WebsocketWorkers <-- MessageTemplates: Шаблоны сообщений
NotificationAdmin <-- MessageTemplates: Шаблоны сообщений
NotificationAPI <--> NotificationsDb: Данные рассылок
NotificationAdmin <--> NotificationsDb: Данные рассылок
@enduml