version: "3.9"
services:
  vertica:
    container_name: vertica
    image: jbfavre/vertica
    ports:
      - "5433:5433"
    volumes:
      - vertica-data:/home/dbadmin/docker
      - ../test_data:/tmp/test_data:ro
volumes:
  vertica-data: